### ISSUE TITLE
Question about critic loss

### ISSUE THREAD

**Issue by qlan3** [luchris429/jitrl#11]
I notice that the implemented critic loss (https://github.com/luchris429/purejaxrl/blob/main/purejaxrl/ppo.py#L179) in PPO is quite different from traditional TD error, more like PPO's actor loss style. Could you please point me to any reference? If there is no such reference, are there any reasons behind for doing so?

**Comment by luchris429** [comment]
Hello! Good question. The code is inspired from [CleanRL's implementation](https://github.com/vwxyzjn/cleanrl/blob/2d660b6d3053ea9037c746b4c9f3a6faa1f20c44/cleanrl/ppo.py#L266), which itself comes from [OpenAI's original implementation](https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/ppo2/model.py#L81-L86).

Costa Huang (author of CleanRL) did an amazing write-up about implementation details [here](https://iclr-blog-track.github.io/2022/03/25/ppo-implementation-details/) -- In Point 9 of the first section he brings up value function loss clipping! Notably, works investigating it find that it does not help performance, and sometimes can even harm performance. However, I include it for the same reasons that Costa does.

**Comment by qlan3** [comment]
Thank you for your quick and helpful reply!
