### ISSUE TITLE
MuJoco Support for weld equality constraint

### ISSUE THREAD

**Issue by reginald-mclean** [luchris429/jitrl#14]
Hi! 
Thanks for releasing this codebase. It's so awesome to see how much faster we can iterate now with tools like this :)

I am just wondering if you attempted to use any environments that use mocaps with weld equality constraints. I am trying to get [Meta-World](https://github.com/Farama-Foundation/Metaworld/) running with Brax and am curious if there's a way around this issue. Thanks!

**Comment by luchris429** [comment]
I have not tried it! To be honest, I'm not fully familiar with what the issue would be exactly 😅

**Comment by luchris429** [comment]
Let me know if there is anything specifically we could do that would help with this!
