### ISSUE TITLE
[Docs] Mention request for JAX-CORL

### ISSUE THREAD

**Issue by nissymori** [luchris429/jitrl#24]
Dear purejaxrl team,

First of all, I would like to express my appreciation for developing the fascinating codebase, purejaxrl
The high-quality single-file implementation in JAX is truly impressive, and I have greatly enjoyed using it, especially PPO(really fast).

As a researcher who predominantly uses JAX due to its speed and efficiency, I recognized the potential value of a offline counterpart of purejaxrl. To address this gap, I recently launched [JAX-CORL](https://github.com/nissymori/JAX-CORL), which provides single-file implementations of Offline RL algorithms specifically in JAX.

I believe that purejaxrl and JAX-CORL can complement each other as online and offline versions of clean RL in JAX. If you find it suitable, I would be happy if you could mention JAX-CORL in the related work section of your README.

Thank you!

**Comment by luchris429** [comment]
That sounds great! Could you open a PR for it?

**Comment by luchris429** [comment]
Actually I just added it. Great work!

**Comment by nissymori** [comment]
@luchris429 Thank you for your mentioning!!!
