### ISSUE TITLE
Trying to run `continuous_mountain_car.py` with `ppo_continuous_action`

### ISSUE THREAD

**Issue by marcdelabarrera** [luchris429/jitrl#26]
As the title says, I'm trying to solve the `gymnax` environment  `continuous_mountain_car.py`. But when using the `BraxGymnaxWrapper`, I get a `KeyError: 'MountainCarContinuous-v0'` because this is not a `brax` environment. Am I missing something? 

I'd like to create my own environment and solve it with `purejaxrl` but I´d like to see `ppo_continuous_action` in action before.

**Comment by luchris429** [comment]
Yeah, `MountainCarContinuous-v0` is not a `brax` environment. You can see the list of them [here!](https://github.com/google/brax/tree/main/brax/envs). 

You should get rid of the `BraxGymnaxWrapper` and just use the Gymnax env directly! The `BraxGymnaxWrapper` turns a Brax env into a gymnax interface.

**Comment by luchris429** [comment]
Let me know if you have any more problems!
